name: Java CI with Maven

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: sub_monitor
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Wait for PostgreSQL
        run: |
          until PGPASSWORD=password psql -h localhost -U user -d sub_monitor -c 'SELECT 1'; do
          echo "Waiting for PostgreSQL..."
          sleep 2
          done
          echo "PostgreSQL ready!"

      - name: Run Liquibase migrations
        run: |
          mvn liquibase:update \
          -Dliquibase.url="jdbc:postgresql://localhost:5432/sub_monitor" \
          -Dliquibase.username=user \
          -Dliquibase.password=password \
          -Dliquibase.changeLogFile="src/main/resources/db/changelog/db.changelog-master.yaml

      - name: Generate JOOQ sources
        run: |
          mvn generate-sources -X \
          -Ddb.url="jdbc:postgresql://localhost:5432/sub_monitor" \
          -Ddb.username=user \
          -Ddb.password=password
          ls -la target/generated-sources/jooq/ru/bicev/submonitor/jooq/ || echo "NO JOOQ FILES!"

      - name: Compile
        run: |
          mvn compile \
          -Ddb.url="jdbc:postgresql://localhost:5432/sub_monitor" \
          -Ddb.username=user \
          -Ddb.password=password